const mongoose = require('mongoose');

/**
 * QRSession Schema
 * Each QR code generated by a teacher creates a session.
 * Sessions expire after TTL (default 45s) and cannot be reused.
 */
const qrSessionSchema = new mongoose.Schema(
  {
    // Unique session identifier embedded in the QR
    sessionId: {
      type: String,
      required: true,
      unique: true,
      index: true,
    },
    // The teacher who generated this session
    teacherId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    // Subject name for the class
    subject: {
      type: String,
      required: [true, 'Subject is required'],
      trim: true,
    },
    // Session expiry timestamp
    expiresAt: {
      type: Date,
      required: true,
      index: { expireAfterSeconds: 0 }, // TTL index auto-deletes expired docs
    },
    // Whether this session is still active
    isActive: {
      type: Boolean,
      default: true,
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model('QRSession', qrSessionSchema);

